# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_stream(
                '/iot_telemetry.DeviceService/StreamTelemetry',
                request_serializer=telemetry__pb2.TelemetryData.SerializeToString,
                response_deserializer=telemetry__pb2.ResetRequest.FromString,
                _registered_method=True)
        self.ResetDevice = channel.unary_unary(
                '/iot_telemetry.DeviceService/ResetDevice',
                request_serializer=telemetry__pb2.ResetRequest.SerializeToString,
                response_deserializer=telemetry__pb2.ResetResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamTelemetry(self, request_iterator, context):
        """🌟 เปลี่ยนเป็น Bidirectional Stream: ส่ง Telemetry ขึ้นไป และรอรับคำสั่ง Reset กลับลงมา
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDevice(self, request, context):
        """🌟 Pi 5 Monitor จะมายิงเรียกฟังก์ชันนี้ที่ Server หลักโดยตรง
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.TelemetryData.FromString,
                    response_serializer=telemetry__pb2.ResetRequest.SerializeToString,
            ),
            'ResetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDevice,
                    request_deserializer=telemetry__pb2.ResetRequest.FromString,
                    response_serializer=telemetry__pb2.ResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iot_telemetry.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iot_telemetry.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/iot_telemetry.DeviceService/StreamTelemetry',
            telemetry__pb2.TelemetryData.SerializeToString,
            telemetry__pb2.ResetRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iot_telemetry.DeviceService/ResetDevice',
            telemetry__pb2.ResetRequest.SerializeToString,
            telemetry__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
