# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\riot_telemetry\"F\n\rTelemetryData\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07voltage\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"1\n\x0cResetRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\" \n\rResetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xab\x01\n\rDeviceService\x12P\n\x0fStreamTelemetry\x12\x1c.iot_telemetry.TelemetryData\x1a\x1b.iot_telemetry.ResetRequest(\x01\x30\x01\x12H\n\x0bResetDevice\x12\x1b.iot_telemetry.ResetRequest\x1a\x1c.iot_telemetry.ResetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYDATA']._serialized_start=34
  _globals['_TELEMETRYDATA']._serialized_end=104
  _globals['_RESETREQUEST']._serialized_start=106
  _globals['_RESETREQUEST']._serialized_end=155
  _globals['_RESETRESPONSE']._serialized_start=157
  _globals['_RESETRESPONSE']._serialized_end=189
  _globals['_DEVICESERVICE']._serialized_start=192
  _globals['_DEVICESERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
